var express = require('express');
var router = express.Router();
var app = require('../controllers/app')
router.post('/api/admin/startlocalchrome', app.startLocalChrome)
router.post('/api/admin/login', app.doLogin)
router.use('/api/admin', app.auth)
router.get('/api/admin/loginjwt', app.doLoginjwt)
router.get('/api/admin/logout', app.logout)
router.post('/api/admin/accounts', app.getAccounts)
router.post('/api/admin/account', app.addAccount)
router.get('/api/admin/account/:id', app.getAccount)
router.post('/api/admin/account/credential/:id', app.saveCredentials)
router.post('/api/admin/account/proxy/:id', app.saveProxy)
router.post('/api/admin/account/tag/:id', app.saveTag)
router.post('/api/admin/account/auto/:id', app.setAuto)
router.post('/api/admin/account/image/:id', app.setImgPath)
router.post('/api/admin/account/bids/:id', app.saveBids)
router.get('/api/admin/account/blocked/:id', app.makeBlocked)
router.get('/api/admin/account/unblocked/:id', app.makeUnblocked)
router.post('/api/admin/account/setclient/:id', app.setClient)
router.post('/api/admin/account/once/:id', app.once)
router.get('/api/admin/account/delete/:id', app.deleteAcc)
router.get('/api/admin/settings', app.getPublicSettings)
router.get('/api/admin/settings/proxy', app.getProxies)
router.get('/api/admin/skills', app.getSkills)
router.post('/api/admin/skills/add', app.addSkills)
router.post('/api/admin/settings/proxy', app.updateProxy)
router.delete('/api/admin/settings/proxy/:_id', app.removeProxy)
router.post('/api/admin/settings/proxy/add', app.addProxy)
router.post('/api/admin/settings/badclient', app.addBadClient)
router.post('/api/admin/settings/manual/register', app.registerManualLink)
router.post('/api/admin/settings/manual/start', app.startManual)
router.post('/api/admin/settings/manual/mark/:id', app.markManualLink)
router.post('/api/admin/settings/keyword/add', app.addKeyword)
router.delete('/api/admin/settings/keyword/:id', app.deleteKeyword)
router.post('/api/admin/settings/skill/add', app.addSkill)
router.delete('/api/admin/settings/skill/:id', app.deleteSkill)
router.post('/api/admin/settings/dictionary/category/add', app.addCategory)
router.post('/api/admin/settings/dictionary/word/add/:id?', app.addWord)
router.post('/api/admin/settings/mails/auto/:id', app.startAutoCreate)
router.get('/api/admin/contracts/:id', app.getContracts)
router.post('/api/admin/contracts', app.doContractAction)
router.post('/api/admin/contracts/actions', app.doContractActions)
router.post('/api/admin/contracts/message', app.sendSimpleMessage)
router.get('/api/admin/contracts/manualescrow/:id', app.manualEscrow)
router.get('/api/admin/jobs/:id', app.getJobs)
router.post('/api/admin/jobs', app.addJob)
router.post('/api/admin/tags', app.addTag)
router.post('/api/admin/tags/edit/:id', app.updateTag)
router.delete('/api/admin/tags/:id', app.removeTag)
// router.post('/api/admin/settings/dictionary/word/edit', app.editWord)

router.post('/webhook', app.firstpromoterWebhook)
module.exports = router 